name: docker-ghcr
run-name: Publish Docker Image to GHCR

on:
  workflow_dispatch:
  push:
    branches:
      - main
      #- no-backfill
    paths-ignore:
      - "docs/**"
      - "README.md"
      - ".env.example"

jobs:
  test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install libvips
        run: |
          sudo apt-get update
          sudo apt-get install -y libvips-dev

      - name: Verify libvips install
        run: vips --version

      - name: Build
        run: go build -v ./...

      - name: Test
        uses: robherley/go-test-action@v0

  build:
    name: Build and push
    needs: test
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      id-token: write
      packages: write
    with:
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      build-args: |
        KOITO_VERSION=dev
      meta-images: ghcr.io/${{ github.repository_owner }}/koito
      meta-tags: |
        type=ref,event=branch
        type=ref,event=pr
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
